In [67]:
import numpy as np
import pandas as pd

In [68]:
import matplotlib.pyplot as mlt
import seaborn as sns

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [70]:
df = pd.read_csv("placementdata.csv")
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                    65               4.4                        No   
1                    90               4.0                       Yes   
2                    82               4.8                       Yes   
3                    85               4.4                       Yes   
4                    86               4.5                       Yes   
...                 ...               ...                       ...   
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                   No         61         79       NotPlaced  
1                  Yes         78         82          Placed  
2                   No         79         80       NotPlaced  
3                  Yes         81         80          Placed  
4                  Yes         74         88          Placed  
...                ...        ...        ...             ...  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced  

[10000 rows x 12 columns]

In [71]:
df.head(5)

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                 65               4.4                        No   
1                 90               4.0                       Yes   
2                 82               4.8                       Yes   
3                 85               4.4                       Yes   
4                 86               4.5                       Yes   

  PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                No         61         79       NotPlaced  
1               Yes         78         82          Placed  
2                No         79         80       NotPlaced  
3               Yes         81         80          Placed  
4               Yes         74         88          Placed

In [72]:
df.tail()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   StudentID                  10000 non-null  int64  
 1   CGPA                       10000 non-null  float64
 2   Internships                10000 non-null  int64  
 3   Projects                   10000 non-null  int64  
 4   Workshops/Certifications   10000 non-null  int64  
 5   AptitudeTestScore          10000 non-null  int64  
 6   SoftSkillsRating           10000 non-null  float64
 7   ExtracurricularActivities  10000 non-null  object 
 8   PlacementTraining          10000 non-null  object 
 9   SSC_Marks                  10000 non-null  int64  
 10  HSC_Marks                  10000 non-null  int64  
 11  PlacementStatus            10000 non-null  object 
dtypes: float64(2), int64(7), object(3)
memory usage: 937.6+ KB


In [74]:
df.describe()

StudentID          CGPA   Internships      Projects  \
count  10000.00000  10000.000000  10000.000000  10000.000000   
mean    5000.50000      7.698010      1.049200      2.026600   
std     2886.89568      0.640131      0.665901      0.867968   
min        1.00000      6.500000      0.000000      0.000000   
25%     2500.75000      7.400000      1.000000      1.000000   
50%     5000.50000      7.700000      1.000000      2.000000   
75%     7500.25000      8.200000      1.000000      3.000000   
max    10000.00000      9.100000      2.000000      3.000000   

       Workshops/Certifications  AptitudeTestScore  SoftSkillsRating  \
count              10000.000000       10000.000000      10000.000000   
mean                   1.013200          79.449900          4.323960   
std                    0.904272           8.159997          0.411622   
min                    0.000000          60.000000          3.000000   
25%                    0.000000          73.000000          4.000000   
50%                    1.000000          80.000000          4.400000   
75%                    2.000000          87.000000          4.700000   
max                    3.000000          90.000000          4.800000   

          SSC_Marks     HSC_Marks  
count  10000.000000  10000.000000  
mean      69.159400     74.501500  
std       10.430459      8.919527  
min       55.000000     57.000000  
25%       59.000000     67.000000  
50%       70.000000     73.000000  
75%       78.000000     83.000000  
max       90.000000     88.000000

In [75]:
df.isnull().sum()

StudentID                    0
CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

In [76]:
df.shape

(10000, 12)

In [77]:
df.columns

Index(['StudentID', 'CGPA', 'Internships', 'Projects',
       'Workshops/Certifications', 'AptitudeTestScore', 'SoftSkillsRating',
       'ExtracurricularActivities', 'PlacementTraining', 'SSC_Marks',
       'HSC_Marks', 'PlacementStatus'],
      dtype='object')

In [78]:
data=df.drop('SSC_Marks',axis = 1,inplace = True)

In [79]:
data1=df.drop('HSC_Marks',axis = 1,inplace = True)

In [80]:
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                    65               4.4                        No   
1                    90               4.0                       Yes   
2                    82               4.8                       Yes   
3                    85               4.4                       Yes   
4                    86               4.5                       Yes   
...                 ...               ...                       ...   
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining PlacementStatus  
0                   No       NotPlaced  
1                  Yes          Placed  
2                   No       NotPlaced  
3                  Yes          Placed  
4                  Yes          Placed  
...                ...             ...  
9995                No       NotPlaced  
9996                No          Placed  
9997               Yes          Placed  
9998               Yes          Placed  
9999                No       NotPlaced  

[10000 rows x 10 columns]

In [81]:
df.rename(columns = {'ExtracurricularActivities':'Extra Activities'},inplace=True)
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating Extra Activities PlacementTraining  \
0                    65               4.4               No                No   
1                    90               4.0              Yes               Yes   
2                    82               4.8              Yes                No   
3                    85               4.4              Yes               Yes   
4                    86               4.5              Yes               Yes   
...                 ...               ...              ...               ...   
9995                 72               3.9              Yes                No   
9996                 90               4.8               No                No   
9997                 70               4.8              Yes               Yes   
9998                 87               4.8              Yes               Yes   
9999                 66               3.8               No                No   

     PlacementStatus  
0          NotPlaced  
1             Placed  
2          NotPlaced  
3             Placed  
4             Placed  
...              ...  
9995       NotPlaced  
9996          Placed  
9997          Placed  
9998          Placed  
9999       NotPlaced  

[10000 rows x 10 columns]

In [82]:
df.columns

Index(['StudentID', 'CGPA', 'Internships', 'Projects',
       'Workshops/Certifications', 'AptitudeTestScore', 'SoftSkillsRating',
       'Extra Activities', 'PlacementTraining', 'PlacementStatus'],
      dtype='object')

In [83]:
from sklearn.preprocessing import OneHotEncoder

In [84]:
ohe = OneHotEncoder()
ohe

OneHotEncoder()

In [85]:
from sklearn.preprocessing import LabelEncoder

In [86]:
le = LabelEncoder()
le

LabelEncoder()

In [87]:
df['Extra Activities'].unique()

array(['No', 'Yes'], dtype=object)

In [88]:
le.fit(df['Extra Activities'])

LabelEncoder()

In [89]:
le.transform(df['Extra Activities'])

array([0, 1, 1, ..., 1, 1, 0], shape=(10000,))

In [90]:
df['Extra Activities'] = le.transform(df['Extra Activities'])

In [91]:
df.head()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating  Extra Activities PlacementTraining  \
0                 65               4.4                 0                No   
1                 90               4.0                 1               Yes   
2                 82               4.8                 1                No   
3                 85               4.4                 1               Yes   
4                 86               4.5                 1               Yes   

  PlacementStatus  
0       NotPlaced  
1          Placed  
2       NotPlaced  
3          Placed  
4          Placed

In [98]:
le.fit(df['PlacementTraining'])

LabelEncoder()

In [100]:
le.fit(df['PlacementTraining'])

array([0, 1, 0, ..., 1, 1, 0], shape=(10000,))

In [101]:
df['PlacementTraining'] = le.transform(df['PlacementTraining'])

In [102]:
df.head()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating  Extra Activities  PlacementTraining  \
0                 65               4.4                 0                  0   
1                 90               4.0                 1                  1   
2                 82               4.8                 1                  0   
3                 85               4.4                 1                  1   
4                 86               4.5                 1                  1   

  PlacementStatus  
0       NotPlaced  
1          Placed  
2       NotPlaced  
3          Placed  
4          Placed

In [104]:
le.fit(df['PlacementStatus'])
le.transform(df['PlacementStatus'])

array([0, 1, 0, ..., 1, 1, 0], shape=(10000,))

In [105]:
df['PlacementStatus'] = le.transform(df['PlacementStatus'])
df.head()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating  Extra Activities  PlacementTraining  \
0                 65               4.4                 0                  0   
1                 90               4.0                 1                  1   
2                 82               4.8                 1                  0   
3                 85               4.4                 1                  1   
4                 86               4.5                 1                  1   

   PlacementStatus  
0                0  
1                1  
2                0  
3                1  
4                1

In [108]:
x = df.drop('PlacementStatus',axis=1)
y = df['PlacementStatus']

In [109]:
x.head()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating  Extra Activities  PlacementTraining  
0                 65               4.4                 0                  0  
1                 90               4.0                 1                  1  
2                 82               4.8                 1                  0  
3                 85               4.4                 1                  1  
4                 86               4.5                 1                  1

y.head()

In [138]:
###when test_size=0.3 and random_state=42###
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3,random_state=42)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (7000, 9)
x_test  (3000, 9)
y_train  (7000,)
y_test  (3000,)


In [139]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([ 0.05752912,  0.34369101, -0.19855754, ...,  0.90497538,
        0.3692428 ,  0.07505461], shape=(3000,))

In [140]:
print("Coefficients:", model.coef_)
print("Intercept:",model.intercept_)

Coefficients: [-2.93189640e-06  7.80661543e-02  1.48125876e-02  7.26916290e-02
  4.26558083e-02  1.30147360e-02  1.15507106e-01  1.56461662e-01
  1.16633011e-01]
Intercept: -2.0817887246876645


In [141]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error",mse)

mean_squared_error 0.14686563473826095


In [143]:
from sklearn.metrics import root_mean_squared_error
rmse =  root_mean_squared_error(y_test,y_pred)
print("root_mean_squared_error",rmse)

root_mean_squared_error 0.38323052427783066


In [144]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mean_absolute_error",mae)

mean_absolute_error 0.3133822894864029


In [151]:
###when test_size=0.3 and random_state=60###
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3,random_state=60)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (7000, 9)
x_test  (3000, 9)
y_train  (7000,)
y_test  (3000,)


In [152]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([ 0.01990582,  0.37768296,  0.05258942, ..., -0.11019324,
        0.36840254,  0.04516564], shape=(3000,))

In [153]:
print("Coefficients:", model.coef_)
print("Intercept:",model.intercept_)

Coefficients: [-9.09419400e-07  7.67328219e-02  1.38274048e-02  7.51462711e-02
  5.01132639e-02  1.25579440e-02  1.13077426e-01  1.51768440e-01
  1.15154877e-01]
Intercept: -2.0444045676478835


In [154]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error",mse)

mean_squared_error 0.1465664813654192


In [155]:
from sklearn.metrics import root_mean_squared_error
rmse =  root_mean_squared_error(y_test,y_pred)
print("root_mean_squared_error",rmse)

root_mean_squared_error 0.38284002059008826


In [156]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mean_absolute_error",mae)

mean_absolute_error 0.31360058764379733


In [159]:
###when test_size=0.2 and random_state=60###
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=60)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (8000, 9)
x_test  (2000, 9)
y_train  (8000,)
y_test  (2000,)


In [160]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0.02181378, 0.38292427, 0.05199994, ..., 0.43169271, 0.15109171,
       0.65627693], shape=(2000,))

In [161]:
print("Coefficients:", model.coef_)
print("Intercept:",model.intercept_)

Coefficients: [-7.46453438e-07  8.06948287e-02  1.12605642e-02  7.25689619e-02
  4.55241862e-02  1.27815569e-02  1.05410477e-01  1.56867505e-01
  1.18757492e-01]
Intercept: -2.0536111149324054


In [162]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error",mse)

mean_squared_error 0.14489883604094195


In [163]:
from sklearn.metrics import root_mean_squared_error
rmse =  root_mean_squared_error(y_test,y_pred)
print("root_mean_squared_error",rmse)

root_mean_squared_error 0.38065579733000515


In [164]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mean_absolute_error",mae)

mean_absolute_error 0.31306001318508975


In [165]:
###when test_size=0.2 and random_state=42###
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (8000, 9)
x_test  (2000, 9)
y_train  (8000,)
y_test  (2000,)


In [166]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pedict=model.predict(x_test)
y_pred

array([0.02181378, 0.38292427, 0.05199994, ..., 0.43169271, 0.15109171,
       0.65627693], shape=(2000,))

In [167]:
print("Coefficients:", model.coef_)
print("Intercept:",model.intercept_)

Coefficients: [-1.83622005e-06  8.04055011e-02  1.43785339e-02  7.52551498e-02
  4.12114333e-02  1.28210718e-02  1.19415420e-01  1.55923759e-01
  1.13823256e-01]
Intercept: -2.1079109310651316


In [168]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error",mse)

mean_squared_error 0.32830747727710996


In [169]:
from sklearn.metrics import root_mean_squared_error
rmse =  root_mean_squared_error(y_test,y_pred)
print("root_mean_squared_error",rmse)

root_mean_squared_error 0.5729812189567036


In [170]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mean_absolute_error",mae)

mean_absolute_error 0.4896745572257707


In [171]:
###when test_size=0.2 and random_state=0###
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=0)
print("x_train ",x_train.shape)
print("x_test ",x_test.shape)
print("y_train ",y_train.shape)
print("y_test ",y_test.shape)

x_train  (8000, 9)
x_test  (2000, 9)
y_train  (8000,)
y_test  (2000,)


In [172]:
model = LinearRegression()
model.fit(x_train,y_train)
y_pedict=model.predict(x_test)
y_pred

array([0.02181378, 0.38292427, 0.05199994, ..., 0.43169271, 0.15109171,
       0.65627693], shape=(2000,))

In [173]:
print("Coefficients:", model.coef_)
print("Intercept:",model.intercept_)

Coefficients: [-5.64419386e-07  7.48112344e-02  1.35689384e-02  7.44040753e-02
  4.12058376e-02  1.25871342e-02  1.14122062e-01  1.72174202e-01
  1.13580595e-01]
Intercept: -2.03605781056511


In [174]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error",mse)

mean_squared_error 0.3302290938828919


In [175]:
from sklearn.metrics import root_mean_squared_error
rmse =  root_mean_squared_error(y_test,y_pred)
print("root_mean_squared_error",rmse)

root_mean_squared_error 0.574655630689278


In [176]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mean_absolute_error",mae)

mean_absolute_error 0.4920847887074974
